### ISSUE TITLE
是否支持windows平台登录?

### ISSUE THREAD

**Issue by jptiancai** [imyouxia/v2ex-login#3]
已配置好`username`和`password`

在`cmd`中运行

```
 python v2ex_auto_login.py
```

输出一下信息,编码有问题

```
Traceback (most recent call last):
  File "v2ex_auto_login.py", line 98, in <module>
    login()
  File "v2ex_auto_login.py", line 70, in login
    raise ValueError,"鐧诲綍澶辫触锛?
ValueError: 鐧诲綍澶辫触锛
```

**Comment by armsword** [comment]
你好，这个代码是在Ubutnu下写的，python版本为2.7。看你的错误，我认为应该是python 3.X的问题。你试试把相关的内容用括号括起来试试，即 raise ValueError("登录失败！")

**Comment by jptiancai** [comment]
我的版本也是2.7,应该是公司代理给闹的.连接之前得创建代理了.
